// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iacoeshrkjkvdwxkpauo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlhY29lc2hya2prdmR3eGtwYXVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTMwMTQsImV4cCI6MjA2NTQ2OTAxNH0.V9zYcY5u1021QxSF6o4ydgYmSWBaG_rCvzhgWRGmySg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);